#!/usr/bin/env bash
# Install and run NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > ~/index.html
sudo cp ~/index.html /var/www/html/index.html
service nginx start
