#!/usr/bin/env bash
# Install and configure NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
touch ~/index.html
echo "Holberton School" > ~/index.html
echo "Ceci n'est pas une page" > ~/404.html
sudo mv ~/404.html /var/www/html/404.html
sudo mv ~/index.html /var/www/html/index.html
redirection="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
notfound="\n\terror_page 404 \/404.html;"
sudo sed -i "s/server_name _;/$redirection$notfound/" /etc/nginx/sites-enabled/default
service nginx start
