#!/usr/bin/env bash
# Install and configure NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > ~/index.html
echo "Ceci n'est pas une page" > ~/404.html
sudo mv ~/404.html /var/www/html/curtom_404.html
sudo mv ~/index.html /var/www/html/index.html
NAME_host=$(uname --all | cut -d " " -f 2)
header=$(echo "add_header X-server-By $NAME_host")
default="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	rewrite ^/redirect_me google.com permanent;
 	$header;
 	}"
echo "$default" > ~/default
sudo mv ~/default /etc/nginx/sites-enabled/default
systemctl start nginx.service

