#!/usr/bin/env bash
# Install and configure NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > ~/index.html
echo "Ceci n'est pas une page" > ~/404.html
sudo mv ~/404.html /var/www/html/custom_404.html
sudo mv ~/index.html /var/www/html/index.html

# NAME_host=$(uname --all | cut -d " " -f 2)

default="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
#	rewrite ^/redirect_me google.com permanent;
	add_header X-Served-By $HOSTNAME;
#	location /redirect_me {
#		return 301 https://lemejiamo.tech;
#	}
	error_page 404 /custom_404.html;
}"
echo "$default" > ~/default
sudo mkdir -p /etc/nginx/sites-enabled
sudo mv ~/default /etc/nginx/sites-enabled/default
sudo service nginx restart
