#!/usr/bin/env bash
# script that configures the container and exec ngnix as ngnix user

sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo -u nginx 'service nginx restart'
